#!/bin/bash
#SBATCH -J matrix_multiplication_8_job
#SBATCH -o matrix_multiplication_8_%j.out
#SBATCH -n 8
#SBATCH -p normal
#SBATCH -t 00:15:00
#SBATCH --mail-user=yohanes.gultom@ui.ac.id
#SBATCH --mail-type=end
ibrun ./matrix_multiplication.o matrix_multiplication.txt
