#!/bin/bash
#SBATCH -J matrix_multiplication_2_job
#SBATCH -o matrix_multiplication_2_%j.out
#SBATCH -n 2
#SBATCH -p normal
#SBATCH -t 01:00:00
#SBATCH --mail-user=yohanes.gultom@ui.ac.id
#SBATCH --mail-type=end
ibrun ./matrix_multiplication.o matrix_multiplication.txt
