mpicc -o gausselim.o gausselim.c -lm &&
echo "NP\tData\tProcess Time" > gausselim.result &&
mpiexec -np 1 ./gausselim.o 700 >> gausselim.result &&
mpiexec -np 1 ./gausselim.o 700 >> gausselim.result &&
mpiexec -np 1 ./gausselim.o 700 >> gausselim.result &&
mpiexec -np 1 ./gausselim.o 700 >> gausselim.result &&
mpiexec -np 1 ./gausselim.o 700 >> gausselim.result &&
mpiexec -np 2 ./gausselim.o 700 >> gausselim.result &&
mpiexec -np 2 ./gausselim.o 700 >> gausselim.result &&
mpiexec -np 2 ./gausselim.o 700 >> gausselim.result &&
mpiexec -np 2 ./gausselim.o 700 >> gausselim.result &&
mpiexec -np 2 ./gausselim.o 700 >> gausselim.result &&
mpiexec -np 4 ./gausselim.o 700 >> gausselim.result &&
mpiexec -np 4 ./gausselim.o 700 >> gausselim.result &&
mpiexec -np 4 ./gausselim.o 700 >> gausselim.result &&
mpiexec -np 4 ./gausselim.o 700 >> gausselim.result &&
mpiexec -np 4 ./gausselim.o 700 >> gausselim.result &&
mpiexec -np 6 ./gausselim.o 700 >> gausselim.result &&
mpiexec -np 6 ./gausselim.o 700 >> gausselim.result &&
mpiexec -np 6 ./gausselim.o 700 >> gausselim.result &&
mpiexec -np 6 ./gausselim.o 700 >> gausselim.result &&
mpiexec -np 6 ./gausselim.o 700 >> gausselim.result &&
mpiexec -np 8 ./gausselim.o 700 >> gausselim.result &&
mpiexec -np 8 ./gausselim.o 700 >> gausselim.result &&
mpiexec -np 8 ./gausselim.o 700 >> gausselim.result &&
mpiexec -np 8 ./gausselim.o 700 >> gausselim.result &&
mpiexec -np 8 ./gausselim.o 700 >> gausselim.result &&
mpiexec -np 1 ./gausselim.o 800 >> gausselim.result &&
mpiexec -np 1 ./gausselim.o 800 >> gausselim.result &&
mpiexec -np 1 ./gausselim.o 800 >> gausselim.result &&
mpiexec -np 1 ./gausselim.o 800 >> gausselim.result &&
mpiexec -np 1 ./gausselim.o 800 >> gausselim.result &&
mpiexec -np 2 ./gausselim.o 800 >> gausselim.result &&
mpiexec -np 2 ./gausselim.o 800 >> gausselim.result &&
mpiexec -np 2 ./gausselim.o 800 >> gausselim.result &&
mpiexec -np 2 ./gausselim.o 800 >> gausselim.result &&
mpiexec -np 2 ./gausselim.o 800 >> gausselim.result &&
mpiexec -np 4 ./gausselim.o 800 >> gausselim.result &&
mpiexec -np 4 ./gausselim.o 800 >> gausselim.result &&
mpiexec -np 4 ./gausselim.o 800 >> gausselim.result &&
mpiexec -np 4 ./gausselim.o 800 >> gausselim.result &&
mpiexec -np 4 ./gausselim.o 800 >> gausselim.result &&
mpiexec -np 6 ./gausselim.o 800 >> gausselim.result &&
mpiexec -np 6 ./gausselim.o 800 >> gausselim.result &&
mpiexec -np 6 ./gausselim.o 800 >> gausselim.result &&
mpiexec -np 6 ./gausselim.o 800 >> gausselim.result &&
mpiexec -np 6 ./gausselim.o 800 >> gausselim.result &&
mpiexec -np 8 ./gausselim.o 800 >> gausselim.result &&
mpiexec -np 8 ./gausselim.o 800 >> gausselim.result &&
mpiexec -np 8 ./gausselim.o 800 >> gausselim.result &&
mpiexec -np 8 ./gausselim.o 800 >> gausselim.result &&
mpiexec -np 8 ./gausselim.o 800 >> gausselim.result

